# Generated by Django 3.2.5 on 2021-11-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_product_product_image_upcomingproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
