# Generated by Django 3.2.5 on 2021-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mainproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
