# Generated by Django 3.2.5 on 2021-11-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211126_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_products',
            field=models.CharField(choices=[('N', 'New'), ('F', 'Featured')], default='F', max_length=1),
        ),
    ]
